version: '2'

volumes:
    mysql_d:

services:
    db:
        image: mysql
        restart: always
        env_file:
            - .env.mysql
        volumes:
            - mysql_d:/var/lib/mysql
    laravel:
        build: ./
        env_file:
            - .env
        ports:
            - 8080:80
        links:
            - db
#        volumes:
#            - .:/var/www
